### ISSUE TITLE
Working on Android 4.3 and 4.4 ?

### ISSUE THREAD

**Issue by brvier** [don/cordova-filechooser#11]
Hi,

I m trying to use your plugin on Android 4.4 and 4.3 (with the genymotion emulator). While the filechooser is well displayed my apps never got success or fail callback.

I m using cordova '5.4.1'.

**Comment by khertan** [comment]
I can see in adb log the following error :
"Got an activity result, but no plugin was registered to receive it"

**Comment by peresbruno** [comment]
Same problem here. Any workaround?
