### ISSUE TITLE
fileChooser is not defined

### ISSUE THREAD

**Issue by boyfox** [don/cordova-filechooser#3]
Hi Don.
Why don't you explain how to declare fileChooser on JavaScript in readme? When I use this plugin appear following error:

04-04 13:33:04.382: I/chromium(21228): [INFO:CONSOLE(15)] "Uncaught ReferenceError: fileChooser is not defined", source: file:///android_asset/html/testing_kitkat2.html (15)

How I can declare instance  FileChooser plugin in JavaScript?

**Comment by santoshshinde2012** [comment]
Hi sir.

 Same issue for me with cordova 5.0.0 , please tell me how can solve this ?
Also please show the simple example to use this plugin , 
thank you in advance.

**Comment by reddysridhar53** [comment]
Hello Sir,

I am getting the same error. I am using cordova 6.3.1. I am injecting it directly in my controller and i am still getting the error. Can you please help me fix this?

**Comment by markeeftb** [comment]
I had the same issue - fileChooser not defined. In my case there was a problem with another plugin which stopped loading the following plugins listed in cordova_plugins.js.

I have moved the filechooser plugin in this file to the top and it started working.
